sonar.organization=310-blueprint
sonar.projectKey=310-Blueprint_fairshare

sonar.sources=backend/src/main/java,backend/src/main/resources,frontend/src
sonar.tests=backend/src/test/java,frontend/test
sonar.java.binaries=backend/target/classes
sonar.java.enablePreview=true
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.exclusions=backend/target/**,frontend/dist/**,frontend/node_modules/**
sonar.qualitygate.wait=true
